### ISSUE TITLE
Create a structure for the GEMDAT tool

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#10]
It might look something like this:

## option 1

- GEMDAT
  - plot_all 
  - plot_1
  - plot_2
  - plot_3

```python
from GEMDAT import plot_1, plot_all
plot_1(<data_and_config>)
plot_all(<data_and_config>)
```
-----------------
Or something like this:

## option 2

- GEMDAT
  - plot(<data_and_config>, <which plots>)
  - plots
    - plot_1(<data_and_config>)
    - plot_2(<data_and_config>)

```python
from GEMDAT import plot
plot(<data_and_config>, ['diffusivity', 'MSD'])  
```
```python
from GEMDAT.plots import plot_diffusivity
plot_diffusivity(<data_and_config>)
```

---------

**data_and_config**:
There will probably be the need to adjust plots with some configuration (splitting into x number of multiple smaller simulations, or cutting away the first few timesteps). I think it would be okay to just pass those through `**kwargs` and let all plot functions accept `**kwargs`, so they can extract those keywords that they will use.
All the possible keywords should be listed in the `plot` (or `plot_all` for option 1) function, but how they are implemented can be explained in the specific `plot_xxx` function.

------------------------

I prefer option two, what are your thoughts about this, @stefsmeets ?

**Comment by v1kko** [comment]
Hmm yes I agree,

how about some structure where the data can be retrieved or calculated (transparently to the user):

```python
from GEMDAT import Data
data = Data()
data.structure = structure #  etc...

from GEMDAT import plot
plot(data=data, cutoff=xxx, all=True)
```
A data object would then be able to provide `Data::jumps` if it was already calculated, or calculate it if it was not yet available.

--------------

The only thing I am then still thinking about is these intermediate files, clearly they are useful, but can we nicely integrate them without the user having to do something like:

```python
from GEMDAT import Data
from pymatgen import VaspRun
data = Data().from_vasprun(VaspRun("xml file")
data.save_intermediate("something")
```

If we have to do something like that, we should think about the correct data-format for such intermediate file.
I would prefer to only have one file containing everything, to not clutter folders, but there is something to be said for saving specific arrays in independent files as well.

**Comment by stefsmeets** [comment]
I'm also wondering to which end we need to cache these intermediate data. So far, none of the computations are particularly demanding. Reading the data is by far the most time consuming.

All the computations I have encountered so far can be vectorized very nicely and run in under a second.

**Comment by v1kko** [comment]
I think its good to define "intermediate" as the data format that can be fed directly to the computations, so after parsing with pymatgen, but before computing extra properties. Because the parsing of pymatgen still takes more than a minute (for me)

**Comment by stefsmeets** [comment]
The `to_dict()` functionality seems horribly inefficient to me. On my computer it takes longer to serialize the data than to read it again from the `vasprun.xml`. It also eats all my memory (10GB+ for the python process) so it's continually swapping to disk.

For small objects (`Lattice`, `Species`, one or two `Structure`s) it seems OK. From what I've seen so far, the data structures in pymatgen are not optimized for the number of time steps we are working with.

I think for this project we will mostly be working with the `Trajectory` class. This is essentially just an array of atomic coordinates. Way more efficient. And even that is easier to store as a numpy file than to go through the `as_dict()` / `from_dict()` machinery.

**Comment by stefsmeets** [comment]
Does it make sense to have some sort of persistant data storage that we can just shove data into when we generate something?

Could something simple like [shelve](https://docs.python.org/3/library/shelve.html) work?

Or maybe something outside the standard library like [klepto](https://github.com/uqfoundation/klepto), which seems like a more flexible big brother of `shelve`.

**Comment by v1kko** [comment]
I like the interface offered by the [numpy.savez](https://numpy.org/doc/stable/reference/generated/numpy.savez.html#numpy.savez) function.
Or otherwise a hdf5 dump might work?

I dislike `shelve` a bit I think as it seems to be based on pickle, which is known to break at times

**Comment by stefsmeets** [comment]
I was thinking about hdf5 as well, don't you find it a bit overkill here?

I was thinking of shelve mainly because the interface is simple (like a python dict), I don't mind that it uses pickle. Pickle usually works well with simple data structures.

I just tried `np.savez` and it also uses pickle on the backend when you pass non-numpy objects (like a python dict). It seems like a nice option too.

```python
from tempfile import TemporaryFile
outfile = TemporaryFile()
np.savez(outfile, data=data, traj_coords=traj_coords)
outfile.seek(0)
npzfile = np.load(outfile, allow_pickle=True)
data2 = npzfile['data'].tolist()  # get the dict back
traj_coords2 = npzfile['traj_coords']
```

**Comment by v1kko** [comment]
Yes, figuring out the same thing here (just not pushed yet :wink: ). so I will add a `numpy.savez` version to  the pull request to have only a single cache file.

**Comment by stefsmeets** [comment]
If we store data using `np.savez` I want to have a small tool that extracts the parameters / metadata to plain test (yaml) so that they can be inspected.

**Comment by v1kko** [comment]
that makes sense, we should store the version/commit_hash of `GEMDAT`, the input file location, maybe the pymatgen version as well.

**Comment by v1kko** [comment]
okay big downside of `numpy.savez` is that it throws away information when saving object, so trying simple `pickle` next, we can take it from there
