### ISSUE TITLE
Add density plot to dashboard

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#124]
As a user of Gemdat,
I want to be view or download the density plot,
So that I can do my analysis without having to write any code

I think we have 2 options:

1. Add a volume viewer to the dashboard
2. Add a way to generate and download the volume in vasp format

Option 1. depends on whether we can find a good volume viewer for the dashboard to display volumes/atomic structures. Otherwise, option 2 would be a good fallback in combination with dedicted crystallographic software like Vesta.

**Comment by v1kko** [comment]
This links to the code @AstyLavrinenko showed us yesterday right? 
Then I suppose we can do option 1. and work together to import the code .

**Comment by stefsmeets** [comment]
Yeah, makes sense. Could be added under a different tab with a link to download the density in vesta format.

**Comment by AstyLavrinenko** [comment]
Yes, and I've just added the function to get the plot that I showed yesterday. But I need some help to integrate it with the main class.

**Comment by stefsmeets** [comment]
I will start working on this now that #160 is implemented.
