### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#13]
This tool lends itself very well for an interactive dashboard.

I would like to have something where you can load your project in the sidebar, set some parameters (like the diffusing element, equilibration time, etc), and have a selector for which plots to generate.

**Comment by v1kko** [comment]
Great idea! 
If we want to have _interactive_ plots the cached data format might help as well to make things responsive

**Comment by v1kko** [comment]
what about: https://docs.kanaries.net/pygwalker/use-pygwalker-with-streamlit.en, we can include both pre-defined plots and let the user play around to make more plots
