### ISSUE TITLE
Documentation Improvements (please add if you think of something)

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#145]
## Notebooks

- [x] Example to save for VESTA
- [x] Example with (legacy) analyse_md, with custom CIF file
- [ ] Example with every property called separately (Alexandros has this)
- [x] A more detailed explanation of the installation process and Python version
- [x] Add shape information for variables presented as arrays, especially those with multiple columns
- [x] Clarify #185 in documentation

**Comment by stefsmeets** [comment]
I think this one can be closed
