### ISSUE TITLE
Specific outputs for users (Add to list if you think of one)

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#146]
### Things to export:

- Sites
- Density
- Volume

### Export to:

- [ ] Matlab

**Comment by stefsmeets** [comment]
I think it will be increasingly difficult to achieve this if we are going down the road of disentangling the original SitesData/Trajectory structures in favour of a hierarchical class structure.

Users can easily achieve this by themselves. The numpy data output can be saved to matlab files via scipy.io.savemat and the dataframes via csv or other columnar format.
