### ISSUE TITLE
develop an example jupyter script

### ISSUE THREAD

**Issue by alexandrosvasi** [GEMDAT-repos/GEMDAT#147]
Make it please

**Comment by v1kko** [comment]
Links to #145

**Comment by stefsmeets** [comment]
Should include density plot: https://github.com/GEMDAT-repos/GEMDAT/pull/160#issuecomment-1768045113

**Comment by stefsmeets** [comment]
This is solved by https://github.com/gemdat-repos/notebooks which are now available from the documentation.
