### ISSUE TITLE
The trajectory objects only have every 10th ionic step in their frame

### ISSUE THREAD

**Issue by v9lgraf** [GEMDAT-repos/GEMDAT#158]
Trajectory.from_vasprun('structures-that_are_already_done_with_MD/vasprun.xml', exception_on_bad_xml=False)

If I execute the above code, the trajectroy has 12378 structures in its frame. 

The actual MD though has 123776 steps (that 10 times more). Somehow the Trajectory.from_structures() constructor by default only includes every 10th step. That can be a good thing because it makes the analysis lighter, but some information may get lost also. 

This needs to be optional. One of the **kwargs in the Trajectory.from_vasprun() should feed into the Trajectory.from_structures() constructor and control how many structures are skipped. 

Again I can provide a vasprun.xml file for you to test, we just have to discuss how I can transfer it to you since we're talking GB size, how was this done with the vasprun.xml file you currently use for testing ?

**Comment by v9lgraf** [comment]
This actually is resolved can be controlled by the adding the ionic_step_skip keyword, got a bit confused with the vasprun.cache file that is created. All clear now

**Comment by v1kko** [comment]
Is this something we should take into account when using the cache?

Perhaps adding the `kwargs` (if present) to the cache filename, so that for each combination of keywords, a cache is generated?
