### ISSUE TITLE
data division only works if len(trajectory)%n_parts==0

### ISSUE THREAD

**Issue by v9lgraf** [GEMDAT-repos/GEMDAT#159]
```python
sites = SitesData(
    structure=s,
    trajectory=trajectory,
    floating_specie='Li',n_parts=10
)
```

Executing the code above throws an error. 

This is resolved by instead running: 

```python
sites = SitesData(
    structure=s,
    trajectory=trajectory,
    floating_specie='Li',n_parts=6
)
```

Note that `len(trajectory) == 12378`. The error is resolved because `12378%6 == 0`.

 `12378%10 != 0` that's why the first code snippet throws an error

This took a while to figure out though and is not robust. **This error should be anticipated. Often the MD step number is not divisible by 10** 

One idea to solve this is clipping some of the final frames from the trajectory so that `len(trajectory)%10==0`. That would at most mean the loss of 0.18 ps of simulation, that is fine considering ~100 ps are run typically. However, when such clipping occurs a warning message should be displayed saying something like"In the course of the data analysis your simulation time was shortened by 0.xx ps"

**Comment by stefsmeets** [comment]
Another option is to have uneven parts, e.g. for 38 with `n_parts=4`: 10, 10, 9, 9
