### ISSUE TITLE
known_material 'mno2_lambda'

### ISSUE THREAD

**Issue by AstyLavrinenko** [GEMDAT-repos/GEMDAT#165]
'mno2_lambda' is a sodium material. However, species are lithium when I'm loading it from known_material. Fix it please

**Comment by stefsmeets** [comment]
The issue is in the cif file: https://github.com/GEMDAT-repos/GEMDAT/blob/main/src/gemdat/data/mno2_lambda.cif

Is it just swapping Li with Na?
