### ISSUE TITLE
Energy landscape: Add units to plots

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#202]
The energy plot is missing units.

**Comment by SCiarella** [comment]
Commit a2a2b3dea2a9b5c14052fdf5fdd6d8246e34b711 solved the issue

**Comment by stefsmeets** [comment]
Nice! But please do not commit directly to main, it makes it difficult to track and test changes.

**Comment by stefsmeets** [comment]
Also, what is this number: `8.61733326e-5`?

Can you define this as a variable or get it from `scipy.constants`?
