### ISSUE TITLE
Refining the jump calculation

### ISSUE THREAD

**Issue by AstyLavrinenko** [GEMDAT-repos/GEMDAT#226]
There is an issue related to the calculation of jumps, specifically concerning atoms fluctuating between the radii of two positions. Currently, this fluctuation is being counted as a jump, which may be inaccurate. To address this issue, we're considering the implementation of an additional constraint to accurately account for atom movement. We have two potential ideas:

1. Time Constraint: The idea is that an atom needs to spend a certain amount of time at the new position for the jump to be counted.
2. Distance Constraint: Alternatively, the atom would need to cross the second radius at a point further from its initial position to be recognized as having jumped.

Our suggestion is to potentially implement both approaches, giving users the flexibility to choose the most suitable constraint for their specific scenarios. Additionally, we propose making the threshold for distance or time a customizable parameter, allowing users to adjust it as needed.

**Comment by v1kko** [comment]
@AstyLavrinenko  I have a question regarding the time constraint, do you prefer this constraint for the whole site, or only for the "inner site" in combination with the distance constraint?

**Comment by AstyLavrinenko** [comment]
> @AstyLavrinenko I have a question regarding the time constraint, do you prefer this constraint for the whole site, or only for the "inner site" in combination with the distance constraint?

Hi @v1kko,
The initial idea was the independent implementation of these two constraints. In this context, the time constraint applies to the entire site.
