### ISSUE TITLE
Use maintained fork for bumpversion

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#227]
https://github.com/callowayproject/bump-my-version

**Comment by v1kko** [comment]
The extra tagging is nice, but  we do that via the github publish workflow currently:
- Publish release, this creates the tag
- github action
  - bump version to tag
  - push back updated version to tag

To me this makes more sense than using bump-my-version, which would need to be executed separately, before publishing a release on github

**Comment by stefsmeets** [comment]
I believe the tagging is also already available in what we use, right?

It came up in a discussion today with @egpbos, who was bothered by all the scattered config files 😅. Bump-my-version supports `pyproject.toml`.

We also use it already here: https://github.com/duqtools/imas2xarray/blob/31e75e8546e2117f107ce1a3150d9571c3f86bc2/pyproject.toml#L170-L186

**Comment by v1kko** [comment]
ah I was confused and believed it was about all the extra features, but yes, for basic tagging (which we indeed already do with bump2version) we can switch to the maintained fork
