### ISSUE TITLE
Add support for custom radii per site type

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#234]
- Get it from a CIF file
- Calculate from temparature factor
- Specify per site type

**Comment by stefsmeets** [comment]
A quick check shows that structures/cifs do not support temperature factors. We could mimick other parts of the code that supply a dict of temperature factors (aka debye-waller factors): https://pymatgen.org/pymatgen.analysis.diffraction.html#pymatgen.analysis.diffraction.neutron.NDCalculator

**Comment by stefsmeets** [comment]
Another option would be to implement B/U iso/aniso in pymatgen. So that it can read the atomic displacement parameters directly from cif and have it available from the site objects. This is probably quite a bit of work.

**Comment by stefsmeets** [comment]
One idea would be to overload the `site_radius` argument:

```python
trajectory.transitions_between_sites(
    ...
    site_radius: {'Li': ..., 'P': ..., 'S': ..., 'Br': ...}
)
```
