### ISSUE TITLE
How to calculate the number of collective jumps

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#235]
It used to be that the number of collective jumps can be much larger than the number of jumps, as every collective jump between jumps is counted.

I added `n_coll_jumps` such that `n_solo_jumps + n_coll_jumps == n_jumps`. If a jump is collective, it is counted _once_ as collective, and solo otherwise.

All the collective jump pairs can still be found inside collective.coll_jumps

Please discuss if this is correct: @alexandrosvasi , @AstyLavrinenko

**Comment by stefsmeets** [comment]
This reflects the situation implemented in #228
