### ISSUE TITLE
Use multiple starting point to compute the MSD

### ISSUE THREAD

**Issue by SCiarella** [GEMDAT-repos/GEMDAT#237]
While calculating the MSD as $$MSD(t-t_0) = \langle |\vec{x}(t)-\vec{x}(t_0)|^2\rangle ,$$ it is possible to obtain better statistics by averaging over different initial values $t_0$.

**Comment by stefsmeets** [comment]
Could you point to some instances where this is relevant for GEMDAT?

**Comment by SCiarella** [comment]
The MSD is calculated in the following situations:
* `_displacements.msd_per_element` to plot a curve representing the MSD
* `_shape.shape` to report the average MSD in the plot title

It is possible to obtain a statistically improved estimation (i.e. a smoother curve or a more representative average) by following this suggestion.

**Comment by stefsmeets** [comment]
I had a look at this and I'm not quite sure how we would implement this. Would you like to have a go at it?

**Comment by SCiarella** [comment]
Yes, sure!
This multiple starting point will also be implemented for the rotations in #220 as discussed with @tfamprikis
