### ISSUE TITLE
SitesData contains data and functions that do not belong there

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#240]
the sitesdata does a lot of extra things that should be separate:

- [x] trajectory
- [x] diff_trajectory
- [x] metrics
- [x] all occupancy methods

These do not belong there, and might be moved, or just removed and computed directly

**Comment by stefsmeets** [comment]
Occupancy is fixed by #246

**Comment by stefsmeets** [comment]
I think the goal for this issue should be to remove `SitesData` completely and move remaining methods to relevant neighbour classes (Jumps, Transitions, Trajectory, Structure)
