### ISSUE TITLE
Problem importing trajectory with newest gemdat version

### ISSUE THREAD

**Issue by v9lgraf** [GEMDAT-repos/GEMDAT#254]
Hi, when executing the following code in the following code in the newest gemdat version:

**Comment by v9lgraf** [comment]
from pathlib import Path

from gemdat import Trajectory
from gemdat.io import read_cif

the following error is given: 

No such file or directory: 'C:\\Users\\vlandgraf\\Anaconda3\\envs\\vic_env_gemdat_4\\Lib\\site-packages\\pymatgen\\io\\vasp\\potcar_summary_stats.json.bz2'

I could not get to the bottom of it. 

Something is fishy with the installation also. I had to install pymatgen in my environment separately ... otherwise it would not work

**Comment by v9lgraf** [comment]
Ok I solved it, I was missing some C++ tools, since my laptop is a bit dated (3.5 years). 

I found a solution in this stack: https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

**Comment by stefsmeets** [comment]
Glad you got it sorted! Seems like a pymatgen issue more than a gemdat issue. I'm going to close this issue, because it seems like you figured it out, but feel free to re-open at any point!
