### ISSUE TITLE
Selecting server-side file with streamlit dashboard `gemdash`

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#26]
The option to select a server-side file seems to be missing.
- There is [file picker](https://docs.streamlit.io/library/api-reference/widgets/st.file_uploader) which does what we want at the client side

Currently this is solved by just having a text input box, which is a bit ugly

**Comment by stefsmeets** [comment]
I came across this:
https://gist.github.com/benlansdell/44000c264d1b373c77497c0ea73f0ef2

**Comment by stefsmeets** [comment]
Yeah, true. It seems to be a long-standing issue. 

I also came accross a solution suggesting to use the tk file picker instead 😅

```python
import tkinter as tk  
from tkinter import filedialog  
if st.button('Upload file'):  
    root = tk.Tk()  
    root.withdraw()  
    file_path = filedialog.askopenfilename()  
    st.image(file_path)
```
