### ISSUE TITLE
Add more plotly plots

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#260]
For consistency, it would be nice if we convert more plots to plotly.

- [x] `plots.displacement_per_site`
- [x] `plots.frequency_vs_occurence`
- [x] `plots.collective_jumps`
- [x] `plots.jumps_3d`

Some of these should be fairly straightforward.

**Comment by v1kko** [comment]
I left those out last time as they do not have an error quantification. But that would make them really easy to convert.
