### ISSUE TITLE
Calculate the Haven's Ratio

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#269]

**Comment by stefsmeets** [comment]
This is essentially the tracer diffusivity of the center of mass of all floating atoms (from the starting point).

**Comment by stefsmeets** [comment]
Haven ratio is defined as:

$H_R = \frac{D^*}{D_\sigma}$

Tracer diffusion (`SimulationMetrics.tracer_diffusivity()`):

$D^*=\frac{1}{3}\int_{0}^{\infty}\left \langle \overline{v(0)}\cdot \overline{v(t)} \right \rangle dt$

Ionic conductivity (essentially `tracer_diffusivity` of center of mass):

$D_\sigma=\frac{1}{3N}\int_{0}^{\infty}\sum_{i,j}^{1...N}\left \langle \overline{v_i(0)}\cdot \overline{v_j(t)} \right \rangle dt$
