### ISSUE TITLE
Plotly output for notebooks might be broken (this is how to fix it)

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#270]
the plotly output for notebooks only outputs a white page,

- A simple fix is wrapping the figure `fig` as `HTML(fig.to_html())` and importing `from IPython.display import HTML`

We should at least document a fix (or use it) so that our notebooks can be run by all users.
`

**Comment by stefsmeets** [comment]
Have you tried some of the solutions proposed in https://github.com/plotly/plotly.py/issues/2508 ?

**Comment by v1kko** [comment]
Another fix is installing jupyter and plotly both from pip

**Comment by stefsmeets** [comment]
Okay, seems that this needs to be fixed in the user installation. Not much more we can do from our side.
