### ISSUE TITLE
Fix displacement plot labels

### ISSUE THREAD

**Issue by SCiarella** [GEMDAT-repos/GEMDAT#273]
The labels of the displacement plots should refer to 'displacement per sites' instead of 'displacement per atoms'

**Comment by v1kko** [comment]
I just updated the plot 'displacement per sites', to 'displacement per atoms' (that's whats actually plotted), can you confirm that this is fixed in the latest documentation? (Then this issue can be closed):
https://gemdat.readthedocs.io/en/latest/notebooks/introduction/

**Comment by SCiarella** [comment]
Looks good!

**Comment by v1kko** [comment]
Closed by #278
