### ISSUE TITLE
VESTA plots

### ISSUE THREAD

**Issue by SCiarella** [GEMDAT-repos/GEMDAT#276]
We have discussed the possibility of interfacing with [VESTA](https://jp-minerals.org/vesta/en/) to plot realistic atomic structures.
Here we can brainstorm about this possibility and what plots could be produced.

**Comment by stefsmeets** [comment]
What does it mean, realistic atomic structures?

**Comment by SCiarella** [comment]
Probably realistic atomic structures is not the correct definition, but I was thinking of something like this:
![linux-main01](https://github.com/GEMDAT-repos/GEMDAT/assets/58949181/6247632b-6f70-45d9-8ab9-2db14c4efba9)

Not sure if this is feasible and useful, though.

**Comment by stefsmeets** [comment]
We sort of already have that. We can store the structure with the density. The density can basically be anything (electron density, free energy, probability, etc). 

https://gemdat.readthedocs.io/en/latest/api/gemdat_volume/#gemdat.volume.Volume.to_vasp_volume

Did you have something else in mind?

**Comment by stefsmeets** [comment]
Do you still want to pick this up @SCiarella ?

**Comment by SCiarella** [comment]
I think we can close this issue and use the plots already implemented in GEMDAT.
