### ISSUE TITLE
rectilinear plot

### ISSUE THREAD

**Issue by tfamprikis** [GEMDAT-repos/GEMDAT#286]
should take a cartesian directory array (e.g. created by `Orientations.get_unit_vectors_trajectory()`) argument alternatively to (instead of?) an `Orientations` object. 

also, right now assumes that a primitive to conventional conversion needs to happen but this should be optional and not default.

**Comment by stefsmeets** [comment]
@SCiarella is this solved by #293?

**Comment by SCiarella** [comment]
I would say that this specific problem is solved.
We will open a new issue if #293 is not general enough.
