### ISSUE TITLE
Rename 'mean squared angular displacement' to 'autocorrelation' everywhere

### ISSUE THREAD

**Issue by SCiarella** [GEMDAT-repos/GEMDAT#297]
In the notebooks and in the `Orientation` class we refer to *mean squared angular displacement*, but in reality what we measure is always the *autocorrelation* (in fact it goes from 1 to 0). 
Correct the name for consistency.

**Comment by stefsmeets** [comment]
Will we have MSAD *and* autocorrelation or just one of them?
