### ISSUE TITLE
Consider using xarray as a data store

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#32]
Some of the data we are generating for the timesteps are well suited for storing in an xarray. Most of the data we are working with are some form of (time step, atom index). 

As dimensions we can use:
- Time
- Labels of the sites or (diffusing) atoms
- Then we can use the parameters per atom/site (occupancy, transition state, speed, etc) as columns in the array

**Comment by v1kko** [comment]
Pandas dataframes are also nice for generating plots, but I think they can be generated quite easily from xarray if needed

**Comment by stefsmeets** [comment]
We are moving to pandas instead,so this can be closed.
