### ISSUE TITLE
MSD plot 

### ISSUE THREAD

**Issue by AstyLavrinenko** [GEMDAT-repos/GEMDAT#329]
In the msd_per_element plot, the mean is currently not represented as a visible line; only the area corresponding to mean ± std is shown. Could you please revert to the previous version where the mean is depicted by a solid line and the std is shown with a semi-transparent shaded area?
![image](https://github.com/GEMDAT-repos/GEMDAT/assets/75916717/7760cc90-4dcd-4cd2-be01-d9e6e1bae7ce)

**Comment by stefsmeets** [comment]
Seems like that is the case to me: https://github.com/GEMDAT-repos/GEMDAT/blob/main/tests/integration/baseline_images/plot_plotly_test/msd_per_element.png

Could you try in non-dark mode?

**Comment by AstyLavrinenko** [comment]
Yeah, looks same 
<img width="733" alt="Capture" src="https://github.com/GEMDAT-repos/GEMDAT/assets/75916717/dc48664b-5245-4c29-9bb9-8776ba8e7b10">

**Comment by stefsmeets** [comment]
Odd, I cannot reproduce this with plotly 5.22, which version are you using?

**Comment by AstyLavrinenko** [comment]
I had 5.20

I upgraded to 5.22, it's better. But still shades are super strong
![image](https://github.com/GEMDAT-repos/GEMDAT/assets/75916717/177ea0fa-5d1d-42ab-8bd4-96dc9df0da31)

**Comment by stefsmeets** [comment]
Can you run the tests?

```
pytest tests/integration/plot_plotly_test.py
```

And let me know if they pass? I'm particularly interested in what the output looks like for `./result_images/plot_plotly_test/msd_per_element.png`.

**Comment by AstyLavrinenko** [comment]
Here is the output:
![msd_per_element](https://github.com/user-attachments/assets/ba216635-f673-4189-bd83-136b0139b0de)
This one looks pretty fine. So I tried to plot more than 500 steps and got the following:
![msd_per_element](https://github.com/user-attachments/assets/27d6ff10-7c2d-47e5-baff-6dff0f4c0347)
When I plot larger trajectory the intensity of errors increased a lot:
![msd_per_element](https://github.com/user-attachments/assets/b4eb68b8-a3f9-4611-b686-c49bbb1483ea)

**Comment by AstyLavrinenko** [comment]
Is it possible to change the transparency of errors somehow? It would be helpful especially when elements are overlapping in a full trajectory plot

**Comment by AstyLavrinenko** [comment]
By the way, I kept having problems running pytest on Windows; it just got stuck. The issue was with saving .png files from plotly. I had to revert to pip install kaleido==0.1.0.post1. Maybe it's worth noting this in the Contributing guidelines.

**Comment by stefsmeets** [comment]
So it seems to be a function of the number of spots then? I wonder if the x axis should be homegenized.

**Comment by stefsmeets** [comment]
This is available in the latest release: https://github.com/GEMDAT-repos/GEMDAT/releases/tag/1.4.0
