### ISSUE TITLE
example notebooks broken - plots backend option

### ISSUE THREAD

**Issue by tfamprikis** [GEMDAT-repos/GEMDAT#333]
Alot (all?) of the jupyter notebooks are now broken, not producing plots. I suspect it is related to the 'backend' argument introduced in 1.3. The plot methods I've tried seem to not work unless backend='matplotlib' is explicitly given. idk if this is a problem with plotly (which I assume is default (?)) or the method definition.

**Comment by stefsmeets** [comment]
Thanks for raising, I'll have a look and get back!

**Comment by stefsmeets** [comment]
Could also be related to this: https://github.com/GEMDAT-repos/GEMDAT/issues/270

**Comment by tfamprikis** [comment]
I was referring to the notebooks on github, e.g. https://github.com/GEMDAT-repos/gemdat-notebooks/blob/main/orientations.ipynb

I have the same problem locally, running scripts in spyder. I just get a blank output like in #270 . Reinstalling plotly from pip didn't help.

**Comment by stefsmeets** [comment]
The github viewer misses a lot of features, so its not a good place to look at notebooks. I don't see any missing plots on nbviewer: https://nbviewer.org/github/GEMDAT-repos/gemdat-notebooks/blob/main/orientations.ipynb

I'm also not familiar with Spyder to give any input there. There is some info on how to render plotly in spyder here: https://plotly.com/python/renderers/

**Comment by tfamprikis** [comment]
thanks, messing with different renderers solved it
