### ISSUE TITLE
Plot vibrational amplitudes

### ISSUE THREAD

**Issue by AstyLavrinenko** [GEMDAT-repos/GEMDAT#335]
The plot of vibrational amplitudes yields different results between matplotlib and plotly backends, with matplotlib showing occurrences up to 2.5 and plotly showing up to 2.0 and appearing more symmetric for some reason.

![image](https://github.com/user-attachments/assets/1807482d-89ab-4fd8-a7dd-044f0fda669f)
![image](https://github.com/user-attachments/assets/fa22953f-029a-4162-b7a1-b4946d20ee22)

Additionally, matplotlib doesn't support `bins` and `n_parts` keywords, which would be beneficial since matplotlib often performs faster and is more convenient in some cases.

**Comment by stefsmeets** [comment]
Hi @AstyLavrinenko thanks for the feedback. The plotly version has 50 bins by default, and the matplotlib version 100. This will cause a difference in the distribution. It would be logital to make these the same. I will update the matplotlib version so that it works similar to the plotly version.

**Comment by AstyLavrinenko** [comment]
Hi @stefsmeets yes I noticed the difference in the default number of bins, so I used `bins=100` for the plotly example.
Thanks! Could you also check other plots for consistency between plotly and matplotlib backends?

**Comment by stefsmeets** [comment]
Most should be ok, but this one must have slipped under the radar. I will have a check 👍
