### ISSUE TITLE
Problem with occupancy function

### ISSUE THREAD

**Issue by AstyLavrinenko** [GEMDAT-repos/GEMDAT#339]
I'm trying to get working functions `transitions.occupancy()` and `transitions.atom_locations()` and getting an error:
![image](https://github.com/user-attachments/assets/631b4f93-68e4-402b-b13d-50b12d1d5bb0)

After fixing `specie` to `species` in the source code, I'm still getting error:
![image](https://github.com/user-attachments/assets/311a8154-551e-47cc-840e-0c6c9c92637a)

Could you please fix that?

Besides that occupancy now seems to appear in the `Structure` object. Is there any additional function to extract average occupancy per each site type?

**Comment by stefsmeets** [comment]
Hi @AstyLavrinenko I cannot reproduce these errors. Which version of pymatgen are you using? And can you post the full traceback?

The choice to return a structure was made to have richer information available to the user. You can easily extract the average occupancy type per site type by looping over the structure.

**Comment by AstyLavrinenko** [comment]
My pymatgen version is 2024.6.10

And full traceback:
```
AttributeError                            Traceback (most recent call last)
Cell In[31], line 1
----> 1 transitions.occupancy()

File \\tudelft.net\staff-umbrella\Project Data akl\gemdat_dev\GEMDAT\src\gemdat\transitions.py:255, in Transitions.occupancy(self)
    252 counts = counts / len(states)
    253 occupancies = dict(zip(unq, counts))
--> 255 species = [{site.species.name: occupancies.get(i, 0)} for i, site in enumerate(sites)]
    257 return Structure(
    258     lattice=sites.lattice,
    259     species=species,
   (...)
    262     labels=sites.labels,
    263 )

File \\tudelft.net\staff-umbrella\Project Data akl\gemdat_dev\GEMDAT\src\gemdat\transitions.py:255, in <listcomp>(.0)
    252 counts = counts / len(states)
    253 occupancies = dict(zip(unq, counts))
--> 255 species = [{site.species.name: occupancies.get(i, 0)} for i, site in enumerate(sites)]
    257 return Structure(
    258     lattice=sites.lattice,
    259     species=species,
   (...)
    262     labels=sites.labels,
    263 )

AttributeError: 'Composition' object has no attribute 'name'
```

Now I'm thinking that it could be because my structure to create transitions already have partial occupation as I took it from experiment
![image](https://github.com/user-attachments/assets/5e49d7df-3525-4d72-9486-dce727d31bc9)


Regarding the average occupancy, the functions you've proposed work only with one type of sites while usually I introduce at least 2-3 different site types. Maybe it worth introducing additional small function to get average occupations

**Comment by stefsmeets** [comment]
What would such an output look like?

**Comment by stefsmeets** [comment]
Okay, I can reproduce the error with a sites structure that has partial occupancy. Not sure if it can be 'fixed' though, because a partial site does not make sense to me.

We can either:
- [ ] Raise an error when the user passes a sites structure with partial occupancies
- [ ] Add work-around by just taking the first element in the list and dropping any disordered species

**Comment by AstyLavrinenko** [comment]
After all, we have three main thing to fix:

- [ ] Before creating `transitions`, an additional validation step is required to check whether the provided structure has partial occupancy on floating species sites or contains any other atoms besides the floating species. If this is the case, the code should adjust the occupancy of all floating species sites to 1 and delete any other sites that are occupied by non-floating species. Additionally, the code should issue a warning to the user, indicating that, for proper analysis, only floating species sites are being considered under the assumption that all of them are fully occupied. Only after this step is completed should the transition object be created.
For my structures, I used `custom_structure.remove_species(['S','Sb','W'])` to delete other species and 
```
for idx,site in enumerate(custom_structure.sites):
    custom_structure.replace(idx=idx, species=site.species.elements[0], label=site.label)
```
to change the occupancy to 1.
- [ ] There is an error in calculating `atom_locations()` from transitions. In the original code it is number of timesteps diffusion atoms spend on the type of sites devided by total number of timesteps and total number of floating species. So, it's like follows without dividing by number of sites of certain type and multipling by total number of sites.
- [ ] There is an error in the current implementation of the `atom_locations()` calculation from `transitions`. In the original MATLAB code, this metric is defined as the ratio of the number of timesteps that diffusion atoms spend on a specific type of site, divided by the total number of timesteps and the total number of floating species. So it shouldn't be divided by the number of sites of that specific type and multiplied by the total number of sites.
```
    def atom_locations(self):
        """Calculate fraction of time atoms spent at a type of site.

        Returns
        -------
        dict[str, float]
            Return dict with the fraction of time atoms spent at a site
        """
        multiplier = 1 / self.n_floating

        compositions_by_label = defaultdict(list)

        for site in self.occupancy():
            compositions_by_label[site.label].append(site.species.num_atoms)

        ret = {}

        for k, v in compositions_by_label.items():
            ret[k] = sum(v)  * multiplier

        return ret
```

- [ ] We need to introduce an additional function to compute the average occupancy for each type of site. This is a crucial metric for analysis 

```
    def average_occupancy(self):
        """Calculate average occupancy per a type of site.

        Returns
        -------
        dict[str, float]
            Return dict with the fraction of time atoms spent at a site
        """

        compositions_by_label = defaultdict(list)

        for site in self.occupancy():
            compositions_by_label[site.label].append(site.species.num_atoms)

        ret = {}

        for k, v in compositions_by_label.items():
            ret[k] = (sum(v) / len(v))

        return ret
```

Could you please do these fixes?

**Comment by stefsmeets** [comment]
I see your point, I just don't see why gemdat needs to do this. This behaviour is difficult to define and to explain. 

The code does not see the disorder, because it only uses the fractional coordinates and site labels. Any specie names are only used for descriptive purposes.


The behaviour you describe would sit behind some sort of flag or toggle, increasing complexity. This would then filter the input sites based on some pre-defined behaviour (floating specie or otherwise), but that is just passing it straight to pymatgen. Therefore I think it is better that the user performs this operation.
