### ISSUE TITLE
Improve nearest site finding algorithm

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#44]
This function: https://github.com/GEMDAT-repos/GEMDAT/blob/b6d6f98e9a25d2f93c7073b2950838581d294bd5/src/sites.py#L195 already takes 15s, and we expect it to become a bottleneck for larger datasets, so we should have a look at it.

Periodic boundaries should be taken into account

Possible paths to explore:
- LazyTensor: http://www.kernel-operations.io/keops/python/api/common/GenericLazyTensor.html
- Some other matrix(multiplication)Operator which is fast and does not store the full matrix
- Custom code from Julia/Rust to define such an operator
- using another method to find the closest neighbours https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html#scipy.spatial.KDTree

**Comment by stefsmeets** [comment]
Note that we are not interested in the distances between all positions, but in the index and distance to the nearest site *only*.

```python
pdist = lattice.get_all_distances(atom_coords, site_coords)

# index of nearest site
nearest = pdist.argmin(axis=1, keepdims=True)

# True if atom is close enough to a site
is_at_site = np.take_along_axis(pdist, nearest, axis=1) < dist_close

# Site index when close, NOSITE when in transition
atom_site = np.where(is_at_site, nearest, NOSITE)
```
