### ISSUE TITLE
Add known materials from matlab code

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#59]
Find/generate structures in CIF format for known materials in matlab code. These are the ones that are available.

- [x] argyrodite, supercell: (1 1 1)
- [x] latp, supercell: (1 1 1)
- [x] na3ps4, supercell: (2 2 2)
- [x] lisnps, supercell: (1 1 1)
- [x] li3ps4_beta, supercell: (1 1 2)
- [x] mno2_lambda, supercell: (1 1 1)
- [x] lagp, supercell: (1 2 2)

**Comment by v1kko** [comment]
When we add this we should also:
- [ ] make it selectable in the dashboard
