### ISSUE TITLE
Rename `structure` argument to SitesData constructor to avoid confusion with `data.structure`

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#62]

**Comment by v1kko** [comment]
for example `material`

**Comment by stefsmeets** [comment]
I don't think it's confusing 😅

**Comment by v1kko** [comment]
as an anecdote: I put `data.structure` where `structure` was expected and then I assumed the plot was broken for a week :smiley:

**Comment by stefsmeets** [comment]
Which plot?

Most of the breakage comes from incompatble lattices between `data.structure` and `sites.structure`. The data generated by the matlab code was using the wrong supercell (1,1,1), should be (2,1,1).

**Comment by v1kko** [comment]
`jumps_vs_distance`

**Comment by stefsmeets** [comment]
Ah, so it's more the number of sites than the lattice. This function does not take structure as an argument though.

**Comment by v1kko** [comment]
sorry I got confused, it is calculating the sitesdata for that plot with 
```
sd = SitesData(data.structure)
```
while it should be
```
structure = load_known_material('argyrodite')
sd = SitesData(structure)
```

That gives an out of bounds error in the plot eventually.
