### ISSUE TITLE
Explore `lxml` for faster loading of `vasprun.xml`

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#8]
Loading a large (~2 GB) `vasprun.xml` using `pymatgen` takes a couple of minutes. 

It's using the standard library xml module to parse the element tree ([see here](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/outputs.py)).

See if we can use a faster library like [lxml](https://lxml.de/intro.html) ([source](https://github.com/lxml/lxml)) to speed this up. It claims to follow the standard library ElementTree API.

**Comment by v1kko** [comment]
I tried it but it is not faster, the bottleneck is probably not the xml parser
