### ISSUE TITLE
Implement conditionals for a jump.

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#91]
There are two main properties which can control this (assuming the sites are defined correctly).
This should be a post-process step after defining the Sites and probably should be specified as parameters for calculating the jumps
- [ ] Time condition: only count a jump if atom remains at new site for certain amount of time.
- [ ] Decrease size of sites: decreases the likelyhood of an oscillation in between the sites generating fake jumps.

**Comment by stefsmeets** [comment]
I made a start with this by isolating the code that calculates the transitions/jumps in `gemdat.transitions`. 

One approach would be to have a `BaseTransitions` class and swap out the code that calculates the transitions in subclasses. This is now done by `_calculate_transition_events`.

**Comment by AstyLavrinenko** [comment]
I think we have duplicated issues with #228
