### ISSUE TITLE
Refactor ported code

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#93]
As we ported more, we realized that some structures could be better represented. this issue is to track that.

- [x] Refactor all calculate functions into "property" functions, which are calculated on demand
  - [x] Also add a toggle to calculate on creation of the object. 
- [x] move diffusive element displacement code into Trajectories
- [x] Remove calculate folder and put calculations in corresponding files
- [x] Refactor all plots to use the Trajectory / Sites / Jumps classes where possible, so that we do not have to pass each property independently 
- [x] Math ( or TrajectoryStatistics) class for statistics concerning Trajectories
- [x] remove diffusive_element specifiers on `Trajectory` functions, and instead allow a view on trajectory, like:
```python
li_trajectory = trajectory.where(element='Li', equilibration_steps=1250)
```
- [x] Better way to include all plots then using `__all__`
- [x] write `trajectory.precompute()` and `sites.precompute()`
- [x] Fix the RDF functions

**Comment by stefsmeets** [comment]
I have fixed all the issues listed here, and implemented all the fixes from #94 in these PRs:
- #98
- #102 
- #105
- #110
- #112
- #114
