### ISSUE TITLE
Bug? Assignment atom_sites_to/from swapped from return in calculate all.

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/GEMDAT#96]
https://github.com/GEMDAT-repos/GEMDAT/blob/b69fc418785dc9efe9b3ecc26f3674497bd1311f/src/sites.py#L68C13-L68C13

**Comment by stefsmeets** [comment]
Ah yes, I mixed up the return statement. A common pitfall when returning tuples 😅

Best would be to check against the `sites.mat` data. It might just be that the assignment on `sites.calculate_all()` is correct, but that I mixed up the variable names inside the method.

**Comment by stefsmeets** [comment]
These seem to be used in the rdf calculation only, and switching them does not change the outcome of the plots.
